### ISSUE TITLE
Update ScalaCheck-DateTime

### ISSUE THREAD

**Issue by MaureenElsberry** [47deg/47deg.github.io#1]
@dialelo Weirdly, when you head over to the page - scalacheck-datetime shows up for about 1 second then disappears.... 

But it should be updated anyways.

ScalaCheck-DateTime is now ScalaCheck-Toolbox

Need to update name and link in listing 

description can be:  Tools for generating sensible data with ScalaCheck.

https://47deg.github.io/scalacheck-toolbox/

**Comment by dialelo** [comment]
The description is taken from the repo description on GitHub, we'd need to edit that in order for the site to show the new description.

**Comment by noelmarkham** [comment]
I've updated the repo description - hasn't changed yet, presume it's cached?

Will check again tomorrow.
